### ISSUE TITLE
Fancybox integration issue

### ISSUE THREAD

**Issue by isabisa** [mikhailkozlov/Picasa-Albums-For-WordPress#11]
Thumbnails won't open in Fancybox when there are multiple values in the rel tag. If you remove the nofollow attribute on line 441 of plugin.php this fixes that problem. Not sure what to do about still making sure those links are nofollow though. Just thought I'd bring it up.

**Comment by mikhailkozlov** [comment]
Thanks for feedback.

This is a tough one. It turns out HTML5 does not allow custom rel values anymore (you can use them, but it will not validate). I have no idea if FB will have new version to support that, so we would have to improvise. 

I lean to wards data-rel attribute, but it will need some testing and we would have to alter Fancybox to accommodate that.

**Comment by mikhailkozlov** [comment]
If you would like to help, checkout v1.0.6 branch. it has fix for the issue.
